name: ckirsch.github.com

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'index.html'
    - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'index.html'
    - 'LICENSE'
  schedule:
    # trigger fridays at 12am
    - cron: '0 0 * * 5'

jobs:
  build-commit-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ckirsch/ckirsch.github.com@main
    - name: Commit
      if: ${{ success() }}
      run: |
        git config --local user.name "Christoph Kirsch"
        git config --local user.email "ckirsch@gmail.com"
        git commit -a -m "Building homepage" || echo "Nothing to commit"
    - name: Push
      if: ${{ success() }}
      run: git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"