name: Github Workflow for ckirsch.github.com

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'index.html'
    - 'LICENSE'
    - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'index.html'
    - 'LICENSE'
    - 'README.md'
  schedule:
    # trigger fridays at 12am
    - cron:  '0 0 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ckirsch/ckirsch.github.com@master
    - name: Commit
      run: |
        git config --local user.name "Homepage Builder"
        git config --local user.email "action@github.com"
        git commit -a -m "Building homepage"