name: Github Workflow for ckirsch.github.com

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'index.html'
    - 'LICENSE'
    - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'index.html'
    - 'LICENSE'
    - 'README.md'
  schedule:
    # trigger fridays at 12am
    - cron:  '0 0 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: ckirsch/ckirsch.github.com@master